module.exports = {
    NULL_VALUE: "필요한 값이 없습니다",
    OUT_OF_VALUE: "필요한 값이 잘못되었습니다",

    SIGN_UP_SUCCESS: "회원가입 성공",
    SIGN_UP_DUPLICATE: "이미 존재하는 회원입니다",
    SIGN_UP_ERROR: "유저 삽입 에러",
    SIGN_IN_SUCCESS: "로그인 성공",
    SIGN_IN_FAIL: "아이디/비밀번호가 틀렸습니다",
    SIGN_IN_ERROR: "유저 조회 에러",

    CATEGORY_INSERT_SUCCESS: "카테고리 작성 성공",
    CATEGORY_UPDATE_SUCCESS: "카테고리 수정 성공",
    CATEGORY_UPDATE_NOTHING: "수정할 카테고리가 존재하지 않습니다",
    CATEGORY_SELECT_SUCCESS: "카테고리 조회 성공",
    CATEGORY_DELETE_SUCCESS: "카테고리 삭제 성공",
    CATEGORY_DELETE_NOTHING: "삭제할 카테고리가 존재하지 않습니다",
    CATEGORY_NON_EXIST: "카테고리가 존재하지 않습니다",
    CATEGORY_INSERT_ERROR:   "카테고리 작성 에러",
    CATEGORY_UPDATE_ERROR:   "카테고리 수정 에러",
    CATEGORY_SELECT_ERROR:   "카테고리 조회 에러",
    CATEGORY_DELETE_ERROR:   "카테고리 삭제 에러",

    HASHTAG_INSERT_SUCCESS: "해시태그 작성 성공",
    HASHTAG_UPDATE_SUCCESS: "해시태그 수정 성공",
    HASHTAG_UPDATE_NOTHING: "수정할 해시태그가 존재하지 않습니다",
    HASHTAG_SELECT_SUCCESS: "해시태그 조회 성공",
    HASHTAG_DELETE_SUCCESS: "해시태그 삭제 성공",
    HASHTAG_DELETE_NOTHING: "삭제할 해시태그가 존재하지 않습니다",
    HASHTAG_NON_EXIST: "해시태그가 존재하지 않습니다",
    HASHTAG_INSERT_ERROR:   "해시태그 작성 에러",
    HASHTAG_UPDATE_ERROR:   "해시태그 수정 에러",
    HASHTAG_SELECT_ERROR:   "해시태그 조회 에러",
    HASHTAG_DELETE_ERROR:   "해시태그 삭제 에러",

    CREATOR_INSERT_SUCCESS: "크리에이터 생성 성공",
    CREATOR_UPDATE_SUCCESS: "크리에이터수정 성공",
    CREATOR_UPDATE_NOTHING: "수정할 크리에이터가 존재하지 않습니다",
    CREATOR_SELECT_SUCCESS: "크리에이터 조회 성공",
    CREATOR_DELETE_SUCCESS: "크리에이터 삭제 성공",
    CREATOR_DELETE_NOTHING: "삭제할 크리에이터가 존재하지 않습니다",
    CREATOR_NON_EXIST: "크리에이터가 존재하지 않습니다",
    CREATOR_INSERT_ERROR:   "크리에이터 작성 에러",
    CREATOR_UPDATE_ERROR:   "크리에이터 수정 에러",
    CREATOR_SELECT_ERROR:   "크리에이터 조회 에러",
    CREATOR_DELETE_ERROR:   "크리에이터 삭제 에러",
    CREATOR_SELECT_PROFILE_SUCCESS : "크리에이터 프로필 조회 성공",
    CREATOR_SELECT_PROFILE_ERROR : "크리에이터 프로필 조회 에러",
    CREATOR_POPULARVIDEO_SELECT_SUCCESS  : "크리에이터 인기영상 조회 성공",
    CREATOR_POPULARVIDEO_SELECT_ERROR: "크리에이터 인기영상 조회 에러",
    CREATOR_NEWVIDEO_SELECT_SUCCESS  : "크리에이터 최신영상 조회 성공",
    CREATOR_NEWVIDEO_SELECT_ERROR: "크리에이터 최신영상 조회 에러",
    CREATOR_CHANNELID_SELECT_ERROR : "크리에이터 채널아이디 조회 에러",
    CREATOR_HOT_SELECT_SUCCESS : "실시간 핫크리에이터 조회 성공",
    CREATOR_HOT_SELECT_ERROR : "실시간 핫크리에이터 조회 성공",
    CREATOR_FOLLOWER_SELECT_SUCCESS : "특정 크리에이터 구독자수 조회 성공" ,
    CREATOR_FOLLOWER_SELECT_ERROR : "특정 크리에이터 구독자수 조회 에러",
    FOLLOWER_SELECT_SUCCESS :" 구독자수 조회 성공" ,
    FOLLOWER_SELECT_ERROR :"구독자수 조회 에러" ,
    CREATOR_LIST_BY_NAME_SELECT_SUCCESS : "크리에이터 검색 성공",
    CREATOR_LIST_BY_NAME_SELECT_ERROR : "크리에이터 검색 에러",
    CREATOR_SEARCH_CNT_INCREASE_UPDATE_ERROR : "크리에이터 검색 수 증가 에러",
    CREATOR_LIST_BY_HASHTAG_SELECT_SUCCESS : "해시태그별 크리에이터 조회 성공",
    CREATOR_LIST_BY_HASHTAG_SELECT_ERROR : "해시태그별 크리에이터 조회 에러",
    CREATOR_LIST_BY_CATEGORY_SELECT_SUCCESS : "카테고리별 크리에이터 조회 성공" ,
    CREATOR_LIST_BY_CATEGORY_SELECT_ERROR : "카테고리별 크리에이터 조회 에러",
    CREATOR_HASHTAG_INSERT_SUCCESS : "크리에이터 해시태그 추가 성공" , 
    CREATOR_HASHTAG_INSERT_ERROR : "크리에이터 해시태그 추가 에러",
    CREATOR_HASHTAG_DELETE_SUCCESS : "크리에이터 해시태그 삭제 성공" , 
    CREATOR_HASHTAG_DELETE_ERROR : "크리에이터 해시태그 삭제 에러",
    CREATOR_CATEGORY_INSERT_SUCCESS : "크리에이터 카테고리 추가 성공" , 
    CREATOR_CATEGORY_INSERT_ERROR : "크리에이터 카테고리 추가 에러",
    CREATOR_CATEGORY_DELETE_SUCCESS : "크리에이터 카테고리 삭제 성공" , 
    CREATOR_CATEGORY_DELETE_ERROR : "크리에이터 카테고리 삭제 에러",
    CREATOR_CUMULATIVE_VIEWS_SELECT_SUCCESS : "크리에이터 누적 조회수 조회 성공", 
    CREATOR_CUMULATIVE_VIEWS_SELECT_ERROR : "크리에이터 누적 조회수 조회 에러", 


    INVALID_TOKEN: "잘못된 형식의 토큰입니다.",
    EMPTY_TOKEN: "토큰값이 존재하지 않습니다.",
    EXPRIED_TOKEN: "만료된 토큰입니다.",
    ONLY_ADMIN: "관리자만 가능한 기능입니다.",
    ONLY_WRITER: "작성자만 가능한 기능입니다.",
    EMPTY_REFRESH_TOKEN: "재발급 토큰이 존재하지 않습니다.",
    CREATE_TOKEN: "토큰 발급 완료.",
    REFRESH_TOKEN: "토큰 재발급 완료.",

    NO_SELECT_AUTHORITY: "조회 권한 없음.",
    USER_SELECTED: "회원 조회 성공.",
    POST_POST_ERROR:"게시글 등록 성공",
    POST_POST_SUCCESS:"게시글 등록 실패",
    POST_BOARD_ERROR:"게시판 등록 실패",
    POST_BOARD_SUCCESS:"게시판 등록 성공",
    GET_BOARD_SEARCH_ERROR:"게시판 검색 실패",
    GET_BOARD_SEARCH_SUCCESS:"게시판 검색 성공",
    BOARD_LIKE_SELECT_SUCCESS:"즐겨찾기한 게시판 조회 성공",
    BOARD_LIKE_SELECT_ERROR:"즐겨찾기한 게시판 조회 실패",
    CREATOR_BOARD_SELECT_SUCCESS:"크리에이터 팬게시판 조회 성공",
    CREATOR_BOARD_SELECT_ERROR:"크리에이터 팬게시판 조회 실패",

    BOARD_DELETE_SUCCESS:"게시판 삭제 성공",
    BOARD_DELETE_NOTHING:"삭제할 게시판이 존재하지 않습니다.",
    BOARD_DELETE_EROOR:"게시판 삭제 실패",
    BOARD_LIKE_INSERT_ERROR:"게시판 즐겨찾기 에러",
    BOARD_LIKE_INSERT_SUCCESS:"게시판 즐겨찾기 성공",
    BOARD_LIKE_INSERT_NOTHING:"즐겨찾기할 게시판이 없습니다.",
    BOARD_LIKE_DELETE_SUCCESS:"게시판 즐겨찾기 취소 성공",
    BOARD_LIKE_DELETE_ERROR:"게시판 즐겨찾기 취소 실패",
    BOARD_LIKE_DELETE_NOTHING:"즐겨찾기 취소할 게시판이 존재하지 않습니다.",
    POST_TODAYHOT_GET_NOTHING:"오늘뜨는 인기글이 존재하지 않습니다.",
    POST_TODAYHOT_GET_ERROR:"오늘뜨는 인기글 조회 실패",
    POST_TODAYHOT_GET_SUCCESS:"오늘뜨는 인기글 조회 성공",
    POST_TODAYNEW_GET_NOTHING:"방금 막 올라온 최신글이 존재하지 않습니다.",
    POST_TODAYNEW_GET_ERROR:"방금 막 올라온 최신글 조회 실패",
    POST_TODAYNEW_GET_SUCCESS:"방금 막 올라온 최신글 조회 성공",
    POST_LIKE_INSERT_SUCCESS:"게시글 좋아요 성공",
    POST_LIKE_INSERT_ERROR:"게시글 좋아요 실패",
    POST_LIKE_DELETE_ERROR:"게시글 좋아요 취소 에러",
    POST_LIKE_DELETE_SUCCESS:"게시글 좋아요 취소 성공",
    POST_HATE_INSERT_ERROR:"게시글 싫어요 에러",
    POST_HATE_INSERT_SUCCESS:"게시글 싫어요 성공",
    POST_HATE_DELETE_SUCCESS:"게시글 싫어요 취소 성공",
    POST_HATE_DELETE_ERROR:"게시글 싫어요 취소 에러",
    POST_POST_IMAGE_ERROR:"게시글 이미지/동영상 등록 실패",
    POST_POST_IMAGE_SUCCESS:"게시글 이미지/동영상 등록 성공",
    POST_UPDATE_SUCCESS:"게시글 수정 성공",
    POST_UPDATE_ERROR:"게시글 수정 에러",
    POST_DELETE_ERROR:"게시글 삭제 에러",
    POST_DELETE_SUCCESS:"게시글 삭제 성공",
    POST_DELETE_NOTHING:"삭제할 게시글이 존재하지 않습니다.",
    POST_BOARD_REQUEST_SUCCESS:"게시판 요청 성공",
    POST_BOARD_REQUEST_ERROR:"게시판 요청 실패",
    GET_BOARD_REQUEST_SUCCESS:"요청 게시판 조회 성공",
    GET_BOARD_REQUEST_ERROR:"요청 게시판 조회 실패",
    COMMENT_INSERT_SUCCESS:"댓글 작성 성공",
    COMMENT_INSERT_ERROR:"댓글 작성 실패",
    POST_SELECT_SUCCESS:"게시글 조회 성공",
    POST_SELECT_ERROR:"게시글 조회 에러",
    COMMENT_UPDATE_ERROR:"댓글 수정 에러",
    COMMENT_UPDATE_SUCCESS:"댓글 수정 성공",
    COMMENT_SELECT_ERROR:"댓글 조회 에러",
    COMMENT_SELECT_SUCCESS:"댓글 조회 성공",
    COMMENT_DELETE_SUCCESS:"댓글 삭제 성공",
    COMMENT_DELETE_ERROR:"댓글 삭제 에러",
    CREATOR_SELECT_STAT_ERROR:"크리에이터 프로필 스탯 조회 에러",
    CREATOR_SELECT_STAT_SUCCESS:"크리에이터 프로필 스탯 조회 성공",
    CREATOR_SELECT_STAT_DETAIL_ERROR:"크리에이터 스탯 상세 등록창 조회 에러",
    CREATOR_SELECT_STAT_DETAIL_SUCCESS:"크리에이터 스탯 상세 등록창 조회 성공",
    STAT_INSERT_ERROR:"스탯 등록 에러",
    STAT_INSERT_SUCCESS:"스탯 등록 성공",
    STAT_HASHTAG_INSERT_ERROR:"해쉬태그 등록 에러",
    STAT_HASHTAG_INSERT_SUCCESS:"해쉬태그 등록 성공",
    BOARD_UNLIKE_SELECT_ERROR:"즐겨찾기 하지 않은 게시판 리스트 조회 에러",
    BOARD_UNLIKE_SELECT_SUCCESS:"즐겨찾기 하지 않은 게시판 리스트 조회 성공",
    GET_BOARD_SEARCH_NOTHING:"게시판 검색 결과가 없습니다.",
    CREATOR_BOARD_SELECT_NOTHING:"크리에이터 팬 게시판 조회 결과가 없습니다.",
    POST_SELECT_NOTHING:"게시글 상세 조회 결과가 없습니다.",
    MEMBERSHIP_INSERT_DUPLICATE:"이미 존재하는 Id입니다.",
    MEMBERSHIP_INSERT_FAIL:"회원가입에 실패했습니다.",
    MEMBERSHIP_INSERT_SUCCESS:"회원가입에 성공했습니다.",
    MEMBERSHIP_ID_NOTHING:"등록 가능한 ID입니다.",
    MEMBERSHIP_ID_EXIST:"이미 존재하는 ID입니다.",

    VOTE_PROGRESSING_SELECT_ERROR: "진행중인 투표 조회 에러",
    VOTE_CHOICE_SELECT_ERROR: "선택지 조회 에러",
    VOTE_PROGRESSING_SELECT_SUCCESS: "진행중인 투표 조회 성공",
    VOTE_PROGRESSING_LIST_SELECT_ERROR: "진행중인 투표 목록 조회 에러",
    VOTE_PROGRESSING_CHOICE_LIST_SELECT_ERROR: "진행중인 투표 목록 선택 에러",
    VOTE_PROGRESSING_LIST_SELECT_SUCCESS: "진행중인 투표 목록 조회 성공",
    VOTE_LAST_SELECT_ERROR: "지난 투표 조회 에러",
    VOTE_LAST_CHOICE_SELECT_ERROR: "지난 투표 선택 에러",
    VOTE_LAST_SELECT_SUCCESS: "지난 투표 조회 성공",
    VOTE_SUGGEST_ERROR: "투표 제안 에러",
    VOTE_SUGGEST_SUCCESS: "투표 제안 성공",
    CREATOR_SELECT_PROFILE_NOTHING:"크리에이터 프로필이 존재하지 않습니다."
};
