module.exports = {
    NULL_VALUE: "필요한 값이 없습니다",
    OUT_OF_VALUE: "필요한 값이 잘못되었습니다",

    SIGN_UP_SUCCESS: "회원가입 성공",
    SIGN_UP_DUPLICATE: "이미 존재하는 회원입니다",
    SIGN_UP_ERROR: "유저 삽입 에러",
    SIGN_IN_SUCCESS: "로그인 성공",
    SIGN_IN_FAIL: "아이디/비밀번호가 틀렸습니다",
    SIGN_IN_ERROR: "유저 조회 에러",

    CATEGORY_INSERT_SUCCESS: "카테고리 작성 성공",
    CATEGORY_UPDATE_SUCCESS: "카테고리 수정 성공",
    CATEGORY_UPDATE_NOTHING: "수정할 카테고리가 존재하지 않습니다",
    CATEGORY_SELECT_SUCCESS: "카테고리 조회 성공",
    CATEGORY_DELETE_SUCCESS: "카테고리 삭제 성공",
    CATEGORY_DELETE_NOTHING: "삭제할 카테고리가 존재하지 않습니다",
    CATEGORY_NON_EXIST: "카테고리가 존재하지 않습니다",
    CATEGORY_INSERT_ERROR:   "카테고리 작성 에러",
    CATEGORY_UPDATE_ERROR:   "카테고리 수정 에러",
    CATEGORY_SELECT_ERROR:   "카테고리 조회 에러",
    CATEGORY_DELETE_ERROR:   "카테고리 삭제 에러",

    HASHTAG_INSERT_SUCCESS: "해시태그 작성 성공",
    HASHTAG_UPDATE_SUCCESS: "해시태그 수정 성공",
    HASHTAG_UPDATE_NOTHING: "수정할 해시태그가 존재하지 않습니다",
    HASHTAG_SELECT_SUCCESS: "해시태그 조회 성공",
    HASHTAG_DELETE_SUCCESS: "해시태그 삭제 성공",
    HASHTAG_DELETE_NOTHING: "삭제할 해시태그가 존재하지 않습니다",
    HASHTAG_NON_EXIST: "해시태그가 존재하지 않습니다",
    HASHTAG_INSERT_ERROR:   "해시태그 작성 에러",
    HASHTAG_UPDATE_ERROR:   "해시태그 수정 에러",
    HASHTAG_SELECT_ERROR:   "해시태그 조회 에러",
    HASHTAG_DELETE_ERROR:   "해시태그 삭제 에러",

    CREATOR_INSERT_SUCCESS: "크리에이터 생성 성공",
    CREATOR_UPDATE_SUCCESS: "크리에이터수정 성공",
    CREATOR_UPDATE_NOTHING: "수정할 크리에이터가 존재하지 않습니다",
    CREATOR_SELECT_SUCCESS: "크리에이터 조회 성공",
    CREATOR_DELETE_SUCCESS: "크리에이터 삭제 성공",
    CREATOR_DELETE_NOTHING: "삭제할 크리에이터가 존재하지 않습니다",
    CREATOR_NON_EXIST: "크리에이터가 존재하지 않습니다",
    CREATOR_INSERT_ERROR:   "크리에이터 작성 에러",
    CREATOR_UPDATE_ERROR:   "크리에이터 수정 에러",
    CREATOR_SELECT_ERROR:   "크리에이터 조회 에러",
    CREATOR_DELETE_ERROR:   "크리에이터 삭제 에러",
    CREATOR_SELECT_PROFILE_SUCCESS : "크리에이터 프로필 조회 성공",
    CREATOR_SELECT_PROFILE_ERROR : "크리에이터 프로필 조회 에러",
    CREATOR_POPULARVIDEO_SELECT_SUCCESS  : "크리에이터 인기영상 조회 성공",
    CREATOR_POPULARVIDEO_SELECT_ERROR: "크리에이터 인기영상 조회 에러",
    CREATOR_HOT_SELECT_SUCCESS : "실시간 핫크리에이터 조회 성공",
    CREATOR_HOT_SELECT_ERROR : "실시간 핫크리에이터 조회 성공",
    CREATOR_FOLLOWER_SELECT_SUCCESS : "특정 크리에이터 구독자수 조회 성공" ,
    CREATOR_FOLLOWER_SELECT_ERROR : "특정 크리에이터 구독자수 조회 에러",
    FOLLOWER_SELECT_SUCCESS :" 구독자수 조회 성공" ,
    FOLLOWER_SELECT_ERROR :"구독자수 조회 에러" ,
    CREATOR_LIST_BY_NAME_SELECT_SUCCESS : "크리에이터별 검색 성공",
    CREATOR_LIST_BY_NAME_SELECT_ERROR : "크리에이터별 검색 에러",
    CREATOR_LIST_BY_HASHTAG_SELECT_SUCCESS : "해시태그별 크리에이터 조회 성공",
    CREATOR_LIST_BY_HASHTAG_SELECT_ERROR : "해시태그별 크리에이터 조회 에러",
    CREATOR_LIST_BY_CATEGORY_SELECT_SUCCESS : "카테고리별 크리에이터 조회 성공" ,
    CREATOR_LIST_BY_CATEGORY_SELECT_ERROR : "카테고리별 크리에이터 조회 에러",
    CREATOR_HASHTAG_INSERT_SUCCESS : "크리에이터 해시태그 추가 성공" , 
    CREATOR_HASHTAG_INSERT_ERROR : "크리에이터 해시태그 추가 에러",
    CREATOR_HASHTAG_DELETE_SUCCESS : "크리에이터 해시태그 삭제 성공" , 
    CREATOR_HASHTAG_DELETE_ERROR : "크리에이터 해시태그 삭제 에러",
    CREATOR_CATEGORY_INSERT_SUCCESS : "크리에이터 해시태그 추가 성공" , 
    CREATOR_CATEGORY_INSERT_ERROR : "크리에이터 해시태그 추가 에러",
    CREATOR_CATEGORY_DELETE_SUCCESS : "크리에이터 해시태그 삭제 성공" , 
    CREATOR_CATEGORY_DELETE_ERROR : "크리에이터 해시태그 삭제 에러",

    INVALID_TOKEN: "잘못된 형식의 토큰입니다.",
    EMPTY_TOKEN: "토큰값이 존재하지 않습니다.",
    EXPRIED_TOKEN: "만료된 토큰입니다.",
    ONLY_ADMIN: "관리자만 가능한 기능입니다.",
    ONLY_WRITER: "작성자만 가능한 기능입니다.",
    EMPTY_REFRESH_TOKEN: "재발급 토큰이 존재하지 않습니다.",
    CREATE_TOKEN: "토큰 발급 완료.",
    REFRESH_TOKEN: "토큰 재발급 완료.",

};